### ISSUE TITLE
Windows and linux builds

### ISSUE THREAD

**Issue by bo0tzz** [ykursadkaya/homebrew-openlens#4]
Thanks for setting this up! It would be nice if this repo could also provide builds for windows and linux.

**Comment by bo0tzz** [comment]
Making cross platform OpenLens builds is also being discussed at https://github.com/lensapp/lens/discussions/5486

**Comment by sbkg0002** [comment]
Don't forget the arm64 OSX build!

**Comment by bo0tzz** [comment]
There's now a cross platform builds setup at https://github.com/MuhammedKalkan/OpenLens
